#! /bin/bash
# Config file for River WM

#  ___                                 
# | _ \_ _ ___  __ _ _ _ __ _ _ __  ___
# |  _/ '_/ _ \/ _` | '_/ _` | '  \(_-<
# |_| |_| \___/\__, |_| \__,_|_|_|_/__/
#               |___/                  

TERMINAL="kitty"
BROWSER="firefox"
FILE_MANAGER="dolphin"
LAUNCHER="rofi"

#    _       _          _            _   
#   /_\ _  _| |_ ___ __| |_ __ _ _ _| |_ 
#  / _ \ || |  _/ _ (_-<  _/ _` | '_|  _|
# /_/ \_\_,_|\__\___/__/\__\__,_|_|  \__|

#  ___                _      
# |_ _|_ _  _ __ _  _| |_ ___
#  | || ' \| '_ \ || |  _(_-<
# |___|_||_| .__/\_,_|\__/__/
#          |_|               
         
# Open a Terminal
riverctl map normal Super Return spawn $TERMINAL

#Close active window
riverctl map normal Super q close

# Change focus using Vim Keys
riverctl map normal Super h focus-view left
riverctl map normal Super j focus-view down
riverctl map normal Super k focus-view up
riverctl map normal Super l focus-view right

# swap windows with Vim Keys
riverctl map normal Super+Shift h swap left
riverctl map normal Super+Shift j swap down
riverctl map normal Super+Shift k swap up
riverctl map normal Super+Shift l swap right

#  ___ _        _ _ 
# / __| |_ _  _| (_)_ _  __ _ 
# \__ \  _| || | | | ' \/ _` |
# |___/\__|\_, |_|_|_||_\__, |
#          |__/         |___/ 

# Tiling layout
riverctl default-layout rivertile

#  _  __         _                      _ 
# | |/ /___ _  _| |__  ___  __ _ _ _ __| |
# | ' </ -_) || | '_ \/ _ \/ _` | '_/ _` |
# |_|\_\___|\_, |_.__/\___/\__,_|_| \__,_|
#           |__/                          

riverctl set-repeat 100 300
